{{- if .Values.backupsEnabled }}
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: {{ include "velero.backupStorageLocation.name" . }}
  annotations:
  {{- if .Values.enableHelmHooks }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
spec:
  provider: {{ include "velero.backupStorageLocation.provider" . }}
{{- with .Values.configuration.backupStorageLocation }}
  objectStorage:
    bucket: {{ .bucket  }}
    {{- with .prefix }}
    prefix: {{ . }}
    {{- end }}
    {{- with .caCert }}
    caCert: {{ . }}
    {{- end }}
  config:
{{- range $key, $value := .config }}
{{- if (eq $key "s3ForcePathStyle") }}
    {{ $key }}: {{ $value | quote }}
{{- else }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
