{{- if or .Values.provider .Values.configuration.provider -}}
{{- $providers := list .Values.provider .Values.backupStorageLocation.provider .Values.volumeSnapshotLocation.provider .Values.configuration.backupStorageLocation.provider .Values.configuration.volumeSnapshotLocation.provider | compact | uniq -}}
{{- $provider := first $providers -}}
{{- $useSecret := or .Values.credentials.existingSecret (or .Values.credentials.secretContents .Values.credentials.extraEnvVars)  -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "velero.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "velero.name" . }}
  template:
    metadata:
      labels:
        name: velero
        app.kubernetes.io/name: {{ include "velero.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "velero.chart" . }}
        {{- if .Values.podLabels }}
          {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    {{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    spec:
      restartPolicy: Always
      serviceAccountName: {{ include "velero.serverServiceAccount" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ include "velero.priorityClassName" . }}
      {{- end }}
      containers:
        - name: velero
          image: {{include "velero.image-from-values" .Values.image }}
          imagePullPolicy: {{ include "velero.pull-policy-from-values" .Values.image }}
          {{- if .Values.metrics.enabled }}
          ports:
            - name: monitoring
              containerPort: 8085
          {{- end }}
          command:
            - /velero
          args:
            - server
          {{- with .Values }}
            {{- with coalesce .configuration.backupSyncPeriod .backupSyncPeriod  }}
            - --backup-sync-period={{ . }}
            {{- end }}
            {{- with coalesce .configuration.resticTimeout .resticTimeout}}
            - --restic-timeout={{ . }}
            {{- end }}
            {{- if coalesce .configuration.restoreOnlyMode .restoreOnlyMode}}
            - --restore-only
            {{- end }}
            {{- with coalesce .configuration.restoreResourcePriorities .restoreResourcePriorities }}
            - --restore-resource-priorities={{ . }}
            {{- end }}
            {{- with coalesce .configuration.features .features }}
            - --features={{ . }}
            {{- end }}
            {{- with coalesce .configuration.logLevel .logLevel }}
            - --log-level={{ . }}
            {{- end }}
            {{- with coalesce .configuration.logFormat .logFormat }}
            - --log-format={{ . }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: plugins
              mountPath: /plugins
        {{- if or .Values.credentials.secretContents .Values.credentials.extraEnvVars }}
            - name: cloud-credentials
              mountPath: /credentials
            - name: scratch
              mountPath: /scratch
        {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          env:
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: LD_LIBRARY_PATH
              value: /plugins
          {{- if $useSecret }}
            {{- if eq $provider "aws" }}
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- else if eq $provider "gcp"}}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /credentials/cloud
            {{- else if eq $provider "azure" }}
            - name: AZURE_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- else if eq $provider "alibabacloud" }}
            - name: ALIBABA_CLOUD_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- end }}
          {{- end }}
          {{- with coalesce .Values.configuration.extraEnvVars .Values.extraEnvVars }}
          {{- range $key, $value := . }}
            - name: {{ default "none" $key | quote }}
              value: {{ default "none" $value | quote }}
          {{- end }}
          {{- end }}
          {{- with .Values.credentials.extraEnvVars }}
          {{- range $key, $value := . }}
            - name: {{ default "none" $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "velero.fullname" $ }}
                  key: {{ default "none" $key }}
          {{- end }}
          {{- end }}
      initContainers:
        {{- $plugins := list -}}
        {{- if kindIs "string" .Values.plugins -}}
          {{- $plugins = splitList "," .Values.plugins -}}
        {{- else -}}
          {{- $plugins = .Values.plugins -}}
        {{- end -}}
        {{- range  $providers -}}
        {{- $plugins = append $plugins (pluck . $.Values.pluginImages | first) }}
        {{- end }}
        {{- range $pluginImage := $plugins }}
        - name: {{ include "velero.name-from-values" $pluginImage }}
          image: {{ include "velero.image-from-values" $pluginImage }}
          imagePullPolicy: {{ include "velero.pull-policy-from-values" $pluginImage }}
          volumeMounts:
            - mountPath: /target
              name: plugins
        {{- end }}
        {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
        {{- end }}


      volumes:
        {{- if $useSecret }}
        - name: cloud-credentials
          secret:
            secretName: {{ include "velero.secretName" . }}
            items:
            - key: {{ .Values.credentials.existingSecretKey }}
              path: cloud
        {{- end }}
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
    {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
