{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "velero.fullname" . }}-server
  labels:
    {{- include "velero.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "velero.serverServiceAccount" . }}
roleRef:
  kind: Role
  name: {{ include "velero.fullname" . }}-server
  apiGroup: rbac.authorization.k8s.io
{{- end }}
