{{- if and .Values.credentials.useSecret (not .Values.credentials.existingSecret) -}}
{{- $root := . }}
{{- range $i, $secret := .Values.credentials.extraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $root.Release.Namespace }}
  {{- with $root.Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    helm.sh/chart: {{ include "velero.chart" $root }}
type: Opaque
data:
{{- range $key, $value := $secret.secretContent }}
  {{ $key }}: {{ tpl $value $root | b64enc }}
{{- end }}
{{- range $key, $value := $secret.extraEnvVars }}
  {{ $key }}: {{ tpl $value $root | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}
